name: Intergration Tests
on:
  workflow_dispatch:  
  push:
    branches:
      - master
  pull_request:
env:
  PAT: ${{ secrets.PAT }}
  ANOTHER_PAT: ${{ secrets.ANOTHER_PAT }}
  OWNER: ${{ secrets.OWNER }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test