name: Intergration Tests
on:
  workflow_dispatch:  
  push:
    branches:
      - main
  pull_request:
env:
  OWNER_NAME: ${{ secrets.OWNER_NAME }}
  OWNER_REPO: ${{ secrets.OWNER_REPO }}
  OWNER_TOKEN: ${{ secrets.OWNER_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test